@startuml TrabalhoTopicos
' skinparam classAttributeIconSize 0

class Usuario {
  - nome : String
  - sobrenome : String
  - email : String
  - senha : String
}

class Cliente {
  - datanascimento : LocalDate
}

class Admin {
  - cnpj : String
}

Usuario <|--  Cliente
Usuario <|--  Admin
Cliente " 1 " --> " * " Endereco

class Endereco {
  - codigo : String
  - rua : String
  - bairro : String
  - numeroLote : String
  - complemento : string
}

Endereco " * " --> " 1 " Cidade
Cidade " * " *--> " 1 " Estado

class Estado {
  - nome : String
  - sigla : String
}

class Cidade {
  - nome : String
}


class CategoriaProduto {
  - nome : String
  - descricao : String
}

class TipoProduto {
  - nome : String
  - descricao : String
}

class Produto {
  - nome : String
  - preco : Double
  - desconto : Double
  - quantidadeDisponivel : Integer
  - descricao : String
  - dataDisponivel : LocalDateTime
}

class ItemVenda {
  - preco : Double
  - quantidade : Integer
}

class Venda {
  - data : LocalDateTime
}

class HistoricoStatus {
  - data: LocalDateTime
}

enum StatusPedido {
  + AGUARDANDO_PAGAMENTO
  + PAGAMENTO_CONFIRMADO
  + EM_PROCESSAMENTO
  + ENVIADO
  + ENTREGUE
  + CANCELADO
}


Venda " * " --> " 1 " Cliente
Venda " 1 " --> " * " ItemVenda
ItemVenda " * " *--> " 1 " Produto
HistoricoStatus " * " *--> " 1 " Venda
HistoricoStatus " * " --> " 1 " StatusPedido


Produto " * " --> " * " TipoProduto
TipoProduto " * " --> " 1 " CategoriaProduto

class Avaliacao {
  - data : LocalDate
  - estrelas : Integer
  - descricao : String
}

enum QuantidadeEstrelas  {
  + UMA : int
  + DUAS : int
  + TRES : int
  + QUATRO : int
  + CINCO : int
}

Avaliacao " * " --> " 1 " QuantidadeEstrelas
Avaliacao " * " --> " 1 " Produto

' class Carrinho {
'   - id : String
' }

' class ProdutoCarrinho {
'   - id : Integer
'   ' - produto : Integer
'   ' - usuario : Integer
'   - quantidade : Integer
' }



' Avaliacao " * " --> " 1 " Produto
' Avaliacao " * " --> " 1 " Usuario
' Cidade " * " o--> " 1 " Estado
' Endereco " * " o--> " 1 " Cidade
' Usuario " 1 " --> " * " Endereco

' Usuario " 1 " --> " * " ProdutoCarrinho
' ProdutoCarrinho " * " -->  " 1 " Produto

' Compra " * " --> " 1 " Usuario
' Compra " 1 " --> " * " ProdutoCompra
' Compra " 1 " --> " * " Endereco
' ProdutoCompra " 1 " --> " 1 " Produto

' Produto " * " o--> " 1 " TipoProduto
' TipoProduto " * " o--> " 1 " CategoriaProduto


@enduml