@startuml TrabalhoTopicos
skinparam classAttributeIconSize 0

class Usuario {
  - nome : String
  - sobrenome : String
  - email : String
  - senha : String
}

class Cliente {
  - datanascimento : LocalDate
}

class Admin {
  - cnpj : String
}

Usuario <|--  Cliente
Usuario <|--  Admin
Usuario " 1 " --> " * " Endereco

class Endereco {
  - codigo : String
  - rua : String
  - bairro : String
  - numeroLote : String
  - complemento : string
}

Endereco " * " --> " 1 " Cidade
Cidade " * " --> " 1 " Estado

class Estado {
  - nome : String
  - sigla : String
}

class Cidade {
  - nome : String
}


class CategoriaProduto {
  - nome : String
  - descricao : String
}

class TipoProduto {
  - nome : String
  - descricao : String
}

class Produto {
  - nome : String
  - preco : Double
  - quantidadedisponivel : Integer
  - descricao : String
  - datadisponivel : LocalDate
}

Produto " * " --> " * " TipoProduto
TipoProduto " * " --> " 1 " CategoriaProduto

class Avaliacao {
  - id : Integer
  - data : LocalDate
  - estrelas : Integer
  - descricao : String
}

' class Carrinho {
'   - id : String
' }

class ProdutoCarrinho {
  - id : Integer
  ' - produto : Integer
  ' - usuario : Integer
  - quantidade : Integer
}

class Compra {
  - id : Integer
  - data : LocalDate
  ' - enderecoentrega : String
  - valortotal : Double
}

class ProdutoCompra {
  - id : Integer
  ' - produto : Integer
  ' - compra : Integer
  - quantidade : Integer
}

' Avaliacao " * " --> " 1 " Produto
' Avaliacao " * " --> " 1 " Usuario
' Cidade " * " o--> " 1 " Estado
' Endereco " * " o--> " 1 " Cidade
' Usuario " 1 " --> " * " Endereco

' Usuario " 1 " --> " * " ProdutoCarrinho
' ProdutoCarrinho " * " -->  " 1 " Produto

' Compra " * " --> " 1 " Usuario
' Compra " 1 " --> " * " ProdutoCompra
' Compra " 1 " --> " * " Endereco
' ProdutoCompra " 1 " --> " 1 " Produto

' Produto " * " o--> " 1 " TipoProduto
' TipoProduto " * " o--> " 1 " CategoriaProduto


@enduml