@startuml Trabalho03
skinparam classAttributeIconSize 0

class Usuario {
  - id : Integer
  - nome : String
  - sobrenome : String
  - datanascimento : LocalDate
  - email : String
  - senha : String
  - privilegio: String
}




class Endereco {
  - id : Integer
  - codigo : String
  - usuario : Integer
  - estado : Integer
  - cidade : Integer
  - rua : String
  - bairro : String
  - numerolote : String
  - complemento : string
}

class Estado {
  id : Integer
  nome : String
  sigla : String
}

class Cidade {
  id : Integer
  nome : String
  estado : Integer
}


class Categoria {
  - id : Integer
  - nome : String
  - descricao : String
}

class Tipo {
  - id : Integer
  - categoria : Integer
  - nome : String
  - descricao : String
}

class Produto {
  - id : Integer
  - nome : String
  - tipo : Integer
  - preco : Double
  - quantidadedisponivel : Integer
  - descricao : String
  - datadisponivel : LocalDate
}

class Avaliacao {
  - id : Integer
  - usuario : integer
  - produto : Integer
  - data : LocalDate
  - estrelas : Integer
  - descricao : String
}

' class Carrinho {
'   - id : String
' }

class ProdutoCarrinho {
  - id : Integer
  - produto : Integer
  - usuario : Integer
  - quantidade : Integer
}

class Compra {
  id : Integer
  data : LocalDate
  usuario : Integer
  enderecoentrega : String
  valortotal : Double
}

class ProdutoCompra {
  id : Integer
  produto : Integer
  compra : Integer
  quantidade : Integer
}


Avaliacao " * " --> " 1 " Produto

Aluno " * " --> " 1 " Orientador : "          "
Usuario " * " o--> " 1 " Plano : "          "
Carro " 1 " *--> " * " Roda : "          "


' conta e plano
' usuario e plano
' casa e garagem
' estado e pais

@enduml